FROM anapsix/alpine

LABEL maintainer="SWUFEFIC" 

WORKDIR /root

COPY . /root/Programs/{{cookiecutter.project_slug}}/
COPY requirements.txt /root

# Prepare the python env
RUN mkdir -p Programs/{{cookiecutter.project_slug}} && mkdir Downloads && \
    wget -P Downloads/ https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    sh -c '/bin/echo -e "\nyes\n\nyes" | sh Downloads/Miniconda3-latest-Linux-x86_64.sh' && \
    ~/miniconda3/bin/pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    rm -rf Downloads